# Server
server:
  port: 8000

spring:
  # profiles
  profiles:
    active: test
  # MySQL
  datasource:
    url: ${url}
    username: ${adminname}
    password: ${password}
    driver-class-name: ${driver-class-name}
  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  # h2
  h2:
    console:
      enabled: true
  # JSP
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /static/**
jwt:
  issuer: ${issuer}
  secret_key: ${secretKey}

logging:
  level:
    root: debug